export const darkTheme = {
  mode: 'dark',
  PRIMARY_BACKGROUND_COLOR: '#212121',
  PRIMARY_TEXT_COLOR: '#FFFFFF',
  PRIMARY_BUTTON_COLOR: '#23A8D9',
  PRIMARY_BUTTON_TEXT_COLOR: '#FFFFFF',
  STATUS_BAR_STYLE: 'dark-content',
};
export const lightTheme = {
  mode: 'light',
  PRIMARY_BACKGROUND_COLOR: '#FFFFFF',
  PRIMARY_TEXT_COLOR: '#212121',
  PRIMARY_BUTTON_COLOR: '#8022D9',
  PRIMARY_BUTTON_TEXT_COLOR: '#FFFFFF',
  STATUS_BAR_STYLE: 'default',
};
